name: Test Build

on: [push, pull_request]

jobs:
  test-build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          - macos-13
          - macos-15
          - ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.3.0
        with:
          node-version: 22

      - name: Install esy
        run: |
          npm install -g esy

      - uses: actions/checkout@v4

      - name: Build
        run: |
          esy
